# Generated by Django 4.0 on 2021-12-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_by_user', models.TextField()),
                ('created_by_user_email', models.EmailField(max_length=254)),
                ('created_by_user_id', models.IntegerField()),
                ('timestamp_initialCreation', models.DateField(auto_now=True)),
                ('timestamp_lastUpdated', models.DateField(auto_now=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
