# Generated by Django 4.0 on 2021-12-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_post_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_by_user',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by_user_email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by_user_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(default=None),
        ),
    ]
