# Generated by Django 4.0 on 2021-12-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_created_by_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_by_user',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by_user_email',
            field=models.EmailField(default='none@nomail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by_user_id',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='No text was entered'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(default='No text was entered'),
        ),
    ]
